# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c212b6bb8f823ef34e778377c98bd7226891e456936924b0d4194f9c1233368def2be9f4d7b5157bb22ce651a06b28187d2e7e6b7fc28aea0a156b0bf10a6d60

test:
  secret_key_base: 96dd0b2e71b8db8e106579417c432979719a29e7540f65b2f0a4a58112209e2846ac30993af4e774d090ea9f37a3e54eb576f04d4d967ccc4bebaa8d8cb9f4b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
